#=====================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description:   Build OpenWrt using ImageBuilder (s905x2 only)
# Instructions:  https://openwrt.org/docs/guide-user/additional-software/imagebuilder
# Download from: https://downloads.openwrt.org/releases
#                https://downloads.immortalwrt.org/releases
#=====================================================================================

name: Build OpenWrt using ImageBuilder (s905x2)

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      releases_branch:
        description: "Select the releases branch"
        required: false
        default: "immortalwrt:24.10.5"
        type: choice
        options:
          - openwrt:25.12.0
          - openwrt:24.10.5
          - openwrt:24.10.4
          - immortalwrt:24.10.5
          - immortalwrt:24.10.4
          - immortalwrt:24.10.3
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "6.12.y_6.18.y"
        type: choice
        options:
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 6.12.y
          - 6.18.y
          - 5.10.y_5.15.y
          - 6.1.y_6.6.y
          - 6.12.y_6.18.y
          - 6.1.y_6.12.y
          - 6.1.y_6.18.y
      auto_kernel:
        description: "Auto use the latest kernel"
        required: false
        default: true
        type: boolean
      kernel_repo:
        description: "Set the kernel repository"
        required: false
        default: "ophub/kernel"
        type: choice
        options:
          - ophub/kernel
      kernel_usage:
        description: "Set the tags of the stable kernel."
        required: false
        default: "stable"
        type: choice
        options:
          - stable
          - flippy
          - beta
      openwrt_ip:
        description: "Set OpenWrt default IP address."
        required: false
        default: "192.168.1.1"
      builder_name:
        description: "Set OpenWrt builder signature."
        required: false
        default: "ophub"
        type: choice
        options:
          - ophub
          - angel
          - yourname

env:
  TZ: Etc/UTC
  IMAGEBUILDER_SH: config/imagebuilder/imagebuilder.sh

jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Initialize the build environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi -f $(docker images -q) 2>/dev/null || true
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-make-openwrt-depends)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          sudo -E timedatectl set-timezone "${TZ:-Etc/UTC}"
          sudo -E ntpdate ntp.ubuntu.com 0.pool.ntp.org || true
          sudo -E timedatectl set-ntp true
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create virtual disk for extended storage
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Build OpenWrt rootfs [ ${{ inputs.releases_branch }} ]
        id: imagebuilder
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: |
          RELEASES_BRANCH="${{ inputs.releases_branch }}"
          chmod +x ${IMAGEBUILDER_SH}
          ${IMAGEBUILDER_SH} ${RELEASES_BRANCH}
          echo "build_tag=OpenWrt_imagebuilder_${RELEASES_BRANCH/:/_}_$(date +"%Y.%m")" >> ${GITHUB_ENV}
          # Create symbolic link for packaging
          [[ -d "/builder/openwrt" ]] || mkdir -p /builder/openwrt
          ln -sf /builder/openwrt /home/runner/work/_actions/ophub/amlogic-s9xxx-openwrt/main/openwrt
          df -hT ${PWD}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload OpenWrt rootfs to Release
        uses: ncipollo/release-action@main
        if: ${{ steps.imagebuilder.outputs.status == 'success' && !cancelled() }}
        with:
          tag: ${{ env.build_tag }}
          artifacts: output/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package OpenWrt for s905x2
        if: ${{ steps.imagebuilder.outputs.status == 'success' && !cancelled() }}
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: output/*rootfs.tar.gz
          openwrt_ip: ${{ inputs.openwrt_ip }}
          openwrt_kernel: ${{ inputs.openwrt_kernel }}
          auto_kernel: ${{ inputs.auto_kernel }}
          kernel_repo: ${{ inputs.kernel_repo }}
          kernel_usage: ${{ inputs.kernel_usage }}
          builder_name: ${{ inputs.builder_name }}

      - name: Upload packaged OpenWrt to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS == 'success' && !cancelled() }}
        with:
          tag: ${{ env.build_tag }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### OpenWrt Image Information
            - Default IP: `192.168.1.1`
            - Default username: `root`
            - Default password: `password`
            - Default WIFI name: `OpenWrt`
            - Default WIFI password: `none`
            ### Install to EMMC
            - Login to OpenWrt → `System` → `Amlogic Service` → `Install OpenWrt`
            ### Applicable Platform
            - 🐧 `arm64`
            - 🐋 Docker image: https://hub.docker.com/u/ophub
